name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.LIGHTSAIL_PRIVATE_KEY }}
          name: lightsail
          known_hosts: ${{ secrets.KNOWN_HOSTS_OF_BASTION }}

      - name: SSH into remote server and deploy
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          port: 22
          key: ${{ secrets.LIGHTSAIL_PRIVATE_KEY }}
          script: |
            # Clone or pull latest code
            cd /home/bitnami/apps/WiiQare-FE
            if [ -d "./.git" ]; then
              git pull origin main
            else
              git@github.com:WiiQare/WiiQare-FE.git .
            fi

            # Install dependencies and build app
            yarn install --frozen-lockfile
            yarn build

            # Restart the application
            pm2 restart 0 --update-env
